[phases.setup]
nixPkgs = ["nodejs_18", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile || npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
PORT = "3000"
NODE_ENV = "production" 