[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install --production=false"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
PORT = "3000"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1" 