steps:
  # Build backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-search-agent-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-search-agent-backend:latest'
      - '.'
    dir: 'backend'

  # Build frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-search-agent-frontend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/web-search-agent-frontend:latest'
      - '.'
    dir: 'frontend'

  # Push backend container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/web-search-agent-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/web-search-agent-backend:latest'

  # Push frontend container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/web-search-agent-frontend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/web-search-agent-frontend:latest'

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'web-search-agent-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/web-search-agent-backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300s'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'
      - '--port'
      - '8000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'PORT=8000'
      - '--set-secrets'
      - 'OPENAI_API_KEY=openai-api-key:latest'

  # Get backend service URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run services describe web-search-agent-backend \
          --region=us-central1 \
          --format='value(status.url)' > /workspace/backend_url.txt

  # Deploy frontend to Cloud Run with backend URL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        gcloud run deploy web-search-agent-frontend \
          --image gcr.io/$PROJECT_ID/web-search-agent-frontend:$COMMIT_SHA \
          --region us-central1 \
          --platform managed \
          --memory 1Gi \
          --cpu 1 \
          --timeout 60s \
          --max-instances 10 \
          --min-instances 0 \
          --port 3000 \
          --allow-unauthenticated \
          --set-env-vars "PORT=3000,NODE_ENV=production,BACKEND_URL=$${BACKEND_URL}"

images:
  - 'gcr.io/$PROJECT_ID/web-search-agent-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/web-search-agent-backend:latest'
  - 'gcr.io/$PROJECT_ID/web-search-agent-frontend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/web-search-agent-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: 2400s 