services:
  # Backend Service
  - type: web
    name: web-search-agent-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements-render.txt"
    startCommand: "python -m uvicorn src.api.main_render:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: OPENAI_API_KEY
        sync: false # Set manually in Render dashboard
    rootDir: backend

  # Frontend Service
  - type: web
    name: web-search-agent-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm ci --legacy-peer-deps && npm run build"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          type: web
          name: web-search-agent-backend
          property: host
      - key: NEXT_PUBLIC_BACKEND_URL
        fromService:
          type: web
          name: web-search-agent-backend
          property: host
    rootDir: frontend 