services:
  # Backend Service
  - type: web
    name: web-search-agent-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install uv && uv sync --frozen && uv run playwright install chromium && uv run playwright install-deps"
    startCommand: "uv run uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: OPENAI_API_KEY
        sync: false # Set manually in Render dashboard
    rootDir: backend

  # Frontend Service
  - type: web
    name: web-search-agent-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        fromService:
          type: web
          name: web-search-agent-backend
          property: host
    rootDir: frontend 