version: '3.8'

services:
  # ChromaDB Vector Database
  chromadb:
    build:
      context: .
      dockerfile: docker/Dockerfile.chromadb
    container_name: rag-chromadb
    ports:
      - "8001:8000"  # ChromaDB on port 8001
    volumes:
      - chromadb_data:/chroma/data
    environment:
      - CHROMA_HOST=0.0.0.0
      - CHROMA_PORT=8000
      - CHROMA_PERSIST_DIRECTORY=/chroma/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - rag-network

  # RAG Agent API
  rag-agent:
    build:
      context: .
      dockerfile: docker/Dockerfile.rag
    container_name: rag-agent
    ports:
      - "8000:8000"  # RAG API on port 8000
    volumes:
      - rag_data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    env_file:
      - .env.docker
    depends_on:
      chromadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - rag-network

  # Redis for Caching (Optional)
  redis:
    image: redis:7-alpine
    container_name: rag-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - rag-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: rag-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - rag-agent
    restart: unless-stopped
    networks:
      - rag-network

volumes:
  chromadb_data:
    driver: local
  rag_data:
    driver: local
  redis_data:
    driver: local

networks:
  rag-network:
    driver: bridge