[phases.setup]
nixPkgs = ["python310", "nodejs", "chromium"]

[phases.install]
cmds = [
  "pip install uv",
  "uv sync --frozen",
  "uv run playwright install chromium",
  "uv run playwright install-deps"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uv run uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1" 