[phases.setup]
nixPkgs = ["python311", "nodejs", "playwright-driver", "chromium"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install uv",
  "uv sync --frozen || (pip install -r requirements.txt && pip install playwright)",
  "playwright install chromium --with-deps"
]

[phases.build]
cmds = [
  "echo 'Build phase complete'"
]

[start]
cmd = "python -m uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"

[variables]
PORT = "8000"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app" 